name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] 
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Sử dụng secret token của bạn
          base: header, activity, community, repositories, metadata
