name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Chạy hàng ngày vào nửa đêm
  workflow_dispatch: # Cho phép chạy thủ công
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Ho_Chi_Minh
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
